### ISSUE TITLE
mechacoach has some online dependencies

### ISSUE THREAD

**Issue by tansaku** [makersacademy/mechacoach#6]
@sjmog three tests fail when mechacoach is disconnected from internet.  Should be stubbed out.

```
Failures:

  1) loading pairs via GUI with an existent cohort name and a well-formed pair file commits the pairs correctly
     Failure/Error: expect(PairAssignments.find('october2015')).to be
     JSON::ParserError:
       A JSON text must at least contain two octets!
     # ./app/models/pair_assignments.rb:10:in `find'
     # ./spec/features/pair_loading_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) FindChannel.with channel exists in Slack returns true
     Failure/Error: expect(described_class.with(existing_channel)).to be true
     SocketError:
       getaddrinfo: nodename nor servname provided, or not known
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier/default_http_client.rb:21:in `call'
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier/default_http_client.rb:8:in `post'
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier.rb:26:in `ping'
     # ./lib/slack_notifier.rb:17:in `notify'
     # ./lib/find_channel.rb:7:in `with'
     # ./spec/find_channel_spec.rb:7:in `block (4 levels) in <top (required)>'

  3) FindChannel.with channel does not exist in Slack returns false
     Failure/Error: expect(described_class.with(non_existent_channel)).to be false
     SocketError:
       getaddrinfo: nodename nor servname provided, or not known
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier/default_http_client.rb:21:in `call'
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier/default_http_client.rb:8:in `post'
     # /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/slack-notifier-1.3.0/lib/slack-notifier.rb:26:in `ping'
     # ./lib/slack_notifier.rb:17:in `notify'
     # ./lib/find_channel.rb:7:in `with'
     # ./spec/find_channel_spec.rb:13:in `block (4 levels) in <top (required)>'

Finished in 0.49034 seconds (files took 0.68056 seconds to load)
46 examples, 3 failures

Failed examples:

rspec ./spec/features/pair_loading_spec.rb:18 # loading pairs via GUI with an existent cohort name and a well-formed pair file commits the pairs correctly
rspec ./spec/find_channel_spec.rb:6 # FindChannel.with channel exists in Slack returns true
rspec ./spec/find_channel_spec.rb:12 # FindChannel.with channel does not exist in Slack returns false
```

**Comment by tansaku** [comment]
@spike01 suggests using webmock as applications does

**Comment by tansaku** [comment]
fixed by https://github.com/makersacademy/mechacoach/pull/12 (we used vcr)
